### ISSUE TITLE
Do not Show Cursor location when in empty note

### ISSUE THREAD

**Issue by chrisgrieser** [spslater/obsidian-cursor-location-plugin#11]
Minor issue similar to #9 – I noticed that when I close the last pane and that pane was in edit mode, the status bar still shows a cursor location – even though an empty pane obviously does not have any sort cursor location.

(In case it helps to resolve this quickly, the Better Word Count Plugin changes the statusbar item when the pane is empty, so the code for this should be there. :) )

**Comment by spslater** [comment]
Yep! Looks like this was solved with merge #13! Should've double checked this issue when writing the commit message, haha.
