### ISSUE TITLE
Bug: Not working in New Editor (CM6)

### ISSUE THREAD

**Issue by chrisgrieser** [spslater/obsidian-cursor-location-plugin#12]
With the new editor (CM6) used by Obsidian 0.13+, the plugin does not seem to work anymore. Multiple cursors are not recognized, and the cursor position is only determined when loading the note, but not when the note changes.

**Comment by gfidias** [comment]
Same here.

**Comment by spslater** [comment]
Sorry for the seemingly abandonment of the project, I am picking it up again. There were some big changes to CM6, so it wasn't a quick fix.
