### ISSUE TITLE
Show the percent of the current line number to the total line number

### ISSUE THREAD

**Issue by langshangyuan** [spslater/obsidian-cursor-location-plugin#15]
# Support Location Percent Display

I think compared to the rigid total line number, people usually are more concerned about the logical location in the whole article.

## Additional Improvement

1. Add more user-friendly settings: 
  - Use the `preamble` indicator when the cursor inside the frontmatter of a markdown file.
  - Use the `top` or `bottom` when the cursor is located on the front part or bottom part of an article.
2. Allow users to use the formatted string style in the setting.
  - I.e. use the placeholder to customize result.

Finally, thank you for your great jobs in creating such plugin. I love it!

**Comment by spslater** [comment]
1. I like this idea, makes a lot of sense. I'll have to look into the preamble and frontmatter, I'm not familiar with that.
2. I'm not super sure what you mean by `top` and `bottom`?
3. I am thinking of adding some more defined string styles and then also letting them customize it. Especially with these new options, I think it could get a bit overwhelming.

**Comment by langshangyuan** [comment]
For the `top` and `bottom`, I want to use them to replace corresponding `0%` and `100%`. Yes, I think after the setting, many people will be satisfied with the default setting. Further customization will be a bit overwhelming.

Thank you for your reply! 😄

**Comment by spslater** [comment]
Ahh, got it, that makes sense! I will start working on it when I have some time this week.
