### ISSUE TITLE
Release v0.3.0: Missing `main.js` asset

### ISSUE THREAD

**Issue by bb010g** [spslater/obsidian-cursor-location-plugin#20]
<https://github.com/spslater/obsidian-cursor-location-plugin/releases/tag/0.3.0> only contains <https://github.com/spslater/obsidian-cursor-location-plugin/releases/download/0.3.0/manifest.json> and <https://github.com/spslater/obsidian-cursor-location-plugin/releases/download/0.3.0/versions.json> assets, preventing installing & enabling the plugin from both Community Plugins and BRAT.

**Comment by spslater** [comment]
Ah shoot! I remembered needing to add two files, just got the wrong files. Uploaded `main.js` to the 0.3.0 release, I'm gonna be working on adding them as part of a github action to prevent this from happening in the future. 

I'll keep this issue open until that action gets created and pushed.
