### ISSUE TITLE
Update values when active window is changed

### ISSUE THREAD

**Issue by dnngll** [spslater/obsidian-cursor-location-plugin#6]
Unfortunately, the values don't change when changing active window. See screenshots:

1: Highlighting 3 lines on the left -> the count is correct
2: Highlighting 5 lines on the right -> the count is correct
3: Switching back to the left window -> the count is wrong, still displaying previous result. The "word" and "character" count are displayed correctly

Screenshots:

1:
![2021 09 12, 15 25 28 Window](https://user-images.githubusercontent.com/12801866/132989497-c8337629-4c2b-4610-bd0e-394b3f92216f.png)

2:
![2021 09 12, 15 25 35 Window](https://user-images.githubusercontent.com/12801866/132989499-f5fbc7e9-f945-4edf-9ce8-9fb20a77b3ec.png)

3:
![2021 09 12, 15 25 42 Window](https://user-images.githubusercontent.com/12801866/132989503-e0f14fd4-33fe-495e-9089-db855c1584b9.png)

**Comment by spslater** [comment]
I've reproduced the problem and will look into it.

I missed it because I was clicking into the different panes so it was updating because the cursor was also updating. Thanks for catching this!

**Comment by dnngll** [comment]
> I've reproduced the problem and will look into it.
> 
> I missed it because I was clicking into the different panes so it was updating because the cursor was also updating. Thanks for catching this!

Nonononono, thank ***you*** for an awesome plugin!
